/**
 * -- DO NOT EDIT THIS FILE --
 * This file is generated automatically during the build process
 * (./configure && make) based on the standard GNU Auto-tools.
 */
package net.jankenpoi.sudokuki;

public interface Version {

    public String versionString = "Sudokuki 1.2";

}
